### PR TITLE
[FIX] Misconfig modification on NerminerV2 branch

### PR DESCRIPTION
**Pull request by twofaktor**
Hi, related to this issue https://github.com/golden-guy/ckpool-solo/issues/5, I opened this PR to fix that

### CODE REVIEW

**Comment by golden-guy** [comment]
Hello, thanks for your input. Indeed I missed to merge this diff config change on the nerdminer_v2 branch. But could you please update all diff values to float, and use these values (since 0.000000001 is way to low - even for a Nerdminer :))

```
"mindiff" : 0.0005,
"startdiff" : 0.0005,
"maxdiff" : 0.0,
```

**Comment by twofaktor** [comment]
> "mindiff" : 0.0005,
> "startdiff" : 0.0005,
> "maxdiff" : 0.0,

Ok, I changed it.

BTW: Did you find out if it is possible to use any of the branches that are supported for Nerdminers and Bitaxes simultaneously?

Probably I will buy a Bitaxe soon and I want to connect it to my pool instance (ckpool) too, the same as I did with my Nerminer, I mean without having to install and run another instance separately

**Comment by golden-guy** [comment]
Hard to tell if this will ever work with a common code base. At least for now you need a seperate instance for your Nerdminers, but running a second instance just creates a small overhead.

**Comment by cprados** [comment]
Hi, sorry if this is not the right place to ask. So for a nerdminer to be seen under /users I I should compile branch nerdminer_v2?

**Comment by golden-guy** [comment]
Yes, and also use the config from the nerdminer_v2 branch as reference.

**Pull request merged**
